import type { Course } from "../types";
import { relatedSlugs } from "../landscape";

const course: Course = {
  slug: "sap-mm",
  name: "SAP MM",
  moduleCode: "MM",
  track: "sap",
  level: "beginner",
  modes: ["online", "classroom"],
  summary:
    "Materials management — procurement from requisition to invoice verification, plus the material master and inventory behind it.",
  duration: "{{MM_DURATION}}",
  batchTimings: "{{MM_BATCH_TIMINGS}}",
  depth: "full",
  overview: [
    "MM covers how a company buys things and what happens to them once they arrive. A requisition becomes a purchase order, the goods arrive and are receipted, the supplier's invoice is checked against both, and only then is the vendor paid. That three-way match is the heart of the module and the reason it exists.",
    "It is also the module with the most visible link to finance. A goods receipt posts an accounting document. Invoice verification clears the GR/IR account. If you understand account determination in MM, you understand why finance and procurement argue, and you become considerably more useful than someone who only knows the screens.",
    "The course works through the full procurement cycle in a live system, then through the special processes that real businesses actually run — subcontracting, consignment, stock transport orders and third-party sales — because those are what interviews are about.",
  ],
  whoFor: [
    "Graduates in commerce, engineering or supply chain looking for a functional SAP role",
    "People working in purchasing, stores or warehouse operations who want to configure the system they use",
    "Career switchers from non-IT backgrounds — MM rewards understanding of how a business buys, not programming",
    "Existing SAP users in other modules who need procurement context",
  ],
  curriculum: [
    {
      title: "Organisational structure and enterprise setup",
      topics: [
        "Company code, plant, storage location and their assignment",
        "Purchasing organisation — plant-specific, cross-plant and cross-company",
        "Purchasing groups and how they drive responsibility",
        "The relationship between the MM structure and the FI and SD structures",
      ],
    },
    {
      title: "Master data",
      topics: [
        "Material master — views, material types, number ranges and field selection",
        "Vendor master — account groups, purchasing data and partner functions",
        "Purchasing info records, source lists and quota arrangements",
        "Batch management basics and serial numbers",
      ],
    },
    {
      title: "The procurement cycle",
      topics: [
        "Purchase requisitions — manual, and generated by MRP",
        "Request for quotation, quotation maintenance and comparison",
        "Purchase orders: document types, item categories and account assignment categories",
        "Release strategies — characteristics, classes and release codes",
        "Outline agreements: contracts and scheduling agreements",
      ],
    },
    {
      title: "Inventory management",
      topics: [
        "Goods receipt against a purchase order, and without reference",
        "Movement types and what each one actually posts — 101, 122, 201, 261, 301, 561",
        "Goods issue, transfer postings and stock transfers",
        "Stock types: unrestricted, quality inspection and blocked",
        "Physical inventory — document creation, counting, differences and posting",
        "Reservations and stock reporting",
      ],
    },
    {
      title: "Invoice verification and valuation",
      topics: [
        "Logistics invoice verification and the three-way match",
        "Tolerance limits, blocked invoices and releasing them",
        "Planned and unplanned delivery costs, subsequent debits and credits",
        "Material valuation, valuation classes and split valuation",
        "Automatic account determination — the account assignment table and the GR/IR clearing account",
        "Price control: standard price against moving average, and what each does to variance",
      ],
    },
    {
      title: "Special procurement processes",
      topics: [
        "Subcontracting — components, the subcontracting purchase order and the 541 movement",
        "Consignment stock and settlement",
        "Stock transport orders within and across company codes",
        "Third-party procurement and its link to sales orders",
        "Returns to vendor",
      ],
    },
    {
      title: "Planning, pricing and reporting",
      topics: [
        "MRP basics — MRP types, lot-sizing procedures and the planning run",
        "The pricing procedure in purchasing: condition types, access sequences and schema determination",
        "Standard reporting for purchase orders, stock and material documents",
        "What changes in S/4HANA: the business partner, the extended material number, and simplified table structures",
      ],
    },
  ],
  liveProject: {
    title: "Set up procurement for a plant and run it through a full cycle",
    description:
      "You configure the organisational structure and master data for a plant, build a release strategy that a purchase order must actually pass through, and then run the cycle: requisition, order, goods receipt, invoice verification, and the postings that result. You then implement a subcontracting process and a stock transport order, and reconcile the GR/IR account when the numbers do not agree — which they will not, deliberately.",
    artefacts: [
      "A configuration document for the organisational structure, document types and release strategy",
      "Material and vendor master records you created, with the reasoning behind the field choices",
      "A traced procure-to-pay cycle showing each document and the accounting entry it produced",
      "A written explanation of the account determination behind those postings",
    ],
  },
  prerequisites: [
    "No programming required — MM is a configuration and process module.",
    "Any exposure to purchasing, stores, logistics or supply chain will make the material land faster, but is not assumed.",
    "Basic accounting vocabulary helps when the module posts to finance. The course covers what you need.",
    "Comfort with a Windows desktop and spreadsheets is sufficient.",
  ],
  roles: [
    "SAP MM functional consultant",
    "SAP MM support consultant",
    "Procurement or materials analyst",
    "Supply chain systems analyst",
  ],
  codes: ["ME21N", "ME51N", "MIGO", "MIRO", "MM01", "ME11", "MB51", "MMBE", "MB5S"],
  related: relatedSlugs("mm"),
  metaDescription:
    "SAP MM course in Pune — procurement, inventory management, invoice verification and account determination, with a live project. Classroom in Narhe and Tilak Road, or online.",
};

export default course;
