// Generated by scripts/optimize-images.mjs — do not edit by hand.

export type Photo = { src: string; width: number; height: number; blurDataURL: string };

export const photos = {
  "classroom": {
    src: "/images/classroom.d0a898b8.webp",
    width: 1024,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABQBQCdASoYABIAPu1srVCppaQiqAqpMB2JaQAALG++E5GnmPGF1ixWzpkjLcNSy6cc/AAA/q+YJ/Mst33NcsQMML+i/IT+uc/1vxKJ4YjJQSsnxXUpKY0zmMB2gugIherwItPbhMZhqCtQq0jkJRDIz4vHdIV98m2WK12VUwoJf8FbGIW31P1ntB2+PpqzNB944/ypjRMwUSTfN5vXbFY0ssMR8j8KQCAAAA==",
  },
  "department": {
    src: "/images/department.859736a2.webp",
    width: 2560,
    height: 1696,
    blurDataURL:
      "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZwAD5bkp5Yv3pAnPBrmdAAD90mGxuv2fQVZ6aXXm3VULO2pyB7xup4Yd3clctISms44/4BxzGjGCa2a57UV6q5XY/0+zBHsvv7qihpZ6FmyNdWKlFAF6Vy0jyF7aGjc27ktMWGkuBMFtMnIwSfCKIGchSbQnJ9Tu2/ileHzKJlaBjAJwAAAA",
  },
  "hod": {
    src: "/images/hod.9f0b3243.webp",
    width: 1080,
    height: 1080,
    blurDataURL:
      "data:image/webp;base64,UklGRhIBAABXRUJQVlA4IAYBAACQBQCdASoYABgAPu1srlKppaQiqAgBMB2JaACdAYyANVUTXFXxvsaS3Iuv177jrabhPymioAD8El6iQXXuMYve8pucBoVvn5E+/E9np109pZibn3S0tjmA+XVT1Xodf2CjcZMhmNNb3VmX4uGXYMFAujrKhXR3PknsDmZZy7ci71k8TF8789Y1S61A1I4LZtEXAKsXdJLNpNX6r+RmFNYTmwEYTPYSM+MYbT4Ay19uFuVhYlXLqb83mSQwAuYHB4wkshg355X3G3f1A+oUCRI4l34cYigH+878/q2vmLSGl/GiKGi9BeBnykTqjSwA7TVV/3jGzhKFMoS/G7qD7IShSXSicAAA",
  },
  "lab-computing": {
    src: "/images/lab-computing.cb2a88b3.webp",
    width: 1024,
    height: 678,
    blurDataURL:
      "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JaQAIEAOPpZml8sgUFYoAAP5adCS4Ji7mDSp+t0JgKAeLRTx1K59zWQiMWOzppOdSNu+vhTYbhPdUrOoUFLs3mF7Y06bk8TzFba1p3Wi02Cfgzrg60Q3nmydpiDtADgYDqGiNb2dyae897pX+VZGvN1PBIMCAAAA=",
  },
  "lab-deep-learning": {
    src: "/images/lab-deep-learning.2891c872.webp",
    width: 1024,
    height: 678,
    blurDataURL:
      "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAAAQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JaADCgYyKhLveP5IP18I6AADJMxAOB4mxlf+j0muuKHi435uOV/rnIJvlFhBkbxpB80aBUm+r13w4dDN1YdxgIOQunsrhg1N7Prs2kZYLSOUP85M+rAlsQVzvQNehuS39UsIY1NgfVqXj+DmwJ45p2FLsu+Xr+u8A97/Up1sP/g9O/1pUroawAAA=",
  },
  "lab-innovation": {
    src: "/images/lab-innovation.29dbda1c.webp",
    width: 1024,
    height: 678,
    blurDataURL:
      "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZQCdBa0WwA3BQrXPWEQGEc+0mtAA6hfOsE7jr36+Ei6Q26WGFU1iSDr/3fMli2m7w3f4zE7M/2csvlS6EgP55ZxCRvsriZrOuwDpOOxKw+uqIOs9+ycNBeHIf/Foq28EAj9gGqVR8xLa+ndyTyV3mqRYAA==",
  },
  "lab-programming": {
    src: "/images/lab-programming.85c7dede.webp",
    width: 1024,
    height: 678,
    blurDataURL:
      "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACQAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZwAAL27EfG7Z664QAPx4V8SfrXh/GlWreVx2XeV7fT8ELE2GDffpfsyz+pfv19GdeFoxYymokYgvsS4yVV8cuOoz+NWBFgBnDNPlpq9LsrdN/8IqgbroyKjm9qK0c3kF9tY7FBKbgOCmfB/XwXAA",
  },
} as const satisfies Record<string, Photo>;

export type PhotoId = keyof typeof photos;
