/**
 * Photo pipeline. Run after adding or replacing anything in assets/photos/:
 *
 *   npm i --no-save sharp && node scripts/optimize-images.mjs
 *
 * For every source photo it writes WebP variants at each width the site's
 * image loader can request (src/lib/image-loader.ts), never upscaling past
 * the source, plus a tiny blurred placeholder. File names carry a content
 * hash, so the CDN can cache them forever and a replaced photo can never be
 * served stale. The manifest it writes (src/content/photos.generated.ts) is
 * the only thing components import.
 *
 * sharp is deliberately not a project dependency: the site never processes
 * images at build or run time, so deployments install nothing native.
 */
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const SRC = path.join(ROOT, "assets/photos");
const OUT = path.join(ROOT, "public/images");
const MANIFEST = path.join(ROOT, "src/content/photos.generated.ts");

// Must match images.imageSizes + images.deviceSizes in next.config.ts.
const WIDTHS = [256, 480, 828, 1080, 1440, 1920];
const QUALITY = 70;

const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png|webp)$/i.test(f)).sort();
await rm(OUT, { recursive: true, force: true });
await mkdir(OUT, { recursive: true });

const entries = [];
for (const file of files) {
  const id = file.replace(/\.[^.]+$/, "");
  const input = await readFile(path.join(SRC, file));
  const hash = createHash("sha1").update(input).digest("hex").slice(0, 8);
  const base = sharp(input).rotate();
  const { width, height } = await base.metadata();
  let bytes = 0;
  for (const w of WIDTHS) {
    const buf = await base
      .clone()
      .resize({ width: Math.min(w, width), withoutEnlargement: true })
      .webp({ quality: QUALITY, effort: 6, smartSubsample: true })
      .toBuffer();
    await writeFile(path.join(OUT, `${id}.${hash}-${w}.webp`), buf);
    bytes += buf.length;
  }
  const blur = await base.clone().resize({ width: 24 }).webp({ quality: 40 }).toBuffer();
  entries.push({
    id,
    src: `/images/${id}.${hash}.webp`,
    width,
    height,
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
  });
  console.log(`${id.padEnd(20)} ${width}x${height}  ${WIDTHS.length} variants, ${(bytes / 1024).toFixed(0)} KB total`);
}

const body = entries
  .map(
    (e) =>
      `  ${JSON.stringify(e.id)}: {\n    src: ${JSON.stringify(e.src)},\n    width: ${e.width},\n    height: ${e.height},\n    blurDataURL:\n      ${JSON.stringify(e.blurDataURL)},\n  },`,
  )
  .join("\n");

await writeFile(
  MANIFEST,
  `// Generated by scripts/optimize-images.mjs — do not edit by hand.\n\nexport type Photo = { src: string; width: number; height: number; blurDataURL: string };\n\nexport const photos = {\n${body}\n} as const satisfies Record<string, Photo>;\n\nexport type PhotoId = keyof typeof photos;\n`,
);
console.log(`\nWrote ${entries.length} photos to public/images and ${path.relative(ROOT, MANIFEST)}`);
